import Head from 'next/head'
// import Image from 'next/image'
// import Script from 'next/script'
import styles from '../styles/Home.module.css'
// import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Busy Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, hunting, blog, hunting coder"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}


      <main className={styles.main}>
        <h1 className={styles.title}>
          Busy <a href="#">Coder</a>
        </h1>
        
      <div className={styles.imgwrap}>
        <img className={styles.codingimg} src="/codingimg.jpeg" width={250} height={166} alt="Laptop image"/>
      </div>

        <p className={styles.description}>
          A blog for busy coders by busy coder
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn javascript in 2021?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2021?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2021?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2021?</h3>
            <p>Javascript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
          Busy Coder
      </footer>
    </div>
  )
}
